import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import SearchInput from "@/components/SearchInput";
import ProductItem from "@/components/ProductItem";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { Props } from "@/types.model";
//
export default function Home({
    data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
    //
    const tabs: string[] = ["Trendy foods", "Bread", "Milk", "Egg"];
    const [activeTab, setActive] = useState<number>(0);
    //
    //
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <SearchInput param={data} />
                <h1 className={styles.title}>
                    Find your favorite products now.
                </h1>
                <div className={styles.tabs}>
                    {tabs.map((tab, index) => (
                        <h1
                            className={
                                index === activeTab ? styles.active : styles.tab
                            }
                            key={`${tab}-${index}`}
                            onClick={() => setActive(index)}
                        >
                            {tab}
                        </h1>
                    ))}
                </div>
                <div className={styles.cardWrapper}>
                    <ProductItem />
                </div>
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps<{
    data: Props;
}> = async (context) => {
    let param: string | string[] = context.query.q || " ";
    try {
        const res = await fetch(
            `https://api.matspar.se/autocomplete?query=${param}`
        );
        const data: Props = {
            data: await res.json(),
            param,
        };
        return {
            props: {
                data,
            },
        };
    } catch (error) {
        const data: Props = {
            data: {
                suggestions: [{ text: "" }],
            },
            param,
        };
        return {
            props: {
                data,
            },
        };
    }
};
