import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import SearchInput from "@/components/SearchInput";
import ProductItem from "@/components/ProductItem";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";

//
export default function Home(
    props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
    //
    const tabs: string[] = ["Trendy foods", "Bread", "Milk", "Egg"];
    const [activeTab, setActive] = useState<number>(0);
    console.log(props);

    //
    //
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <SearchInput />
                <h1 className={styles.title}>
                    Find your favorite products now.
                </h1>
                <div className={styles.tabs}>
                    {tabs.map((tab, index) => (
                        <h1
                            className={
                                index === activeTab ? styles.active : styles.tab
                            }
                            key={`${tab}-${index}`}
                            onClick={() => setActive(index)}
                        >
                            {tab}
                        </h1>
                    ))}
                </div>
                <div className={styles.cardWrapper}>
                    <ProductItem />
                </div>
            </main>
        </>
    );
}

type Data = {
    suggestions: [{ test: string }];
};

export const getServerSideProps: GetServerSideProps<{ data: Data }> = async (
    context
) => {
    const res = await fetch(
        `https://api.matspar.se/autocomplete?query=${context.query.q}`
    );
    const data: Data = await res.json();
    let param: any = context.query.q;
    return {
        props: {
            data,
            param,
        },
    };
};
